# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-01-25 07:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import forms_builder.forms.models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20160418_0120'),
    ]

    operations = [
        migrations.CreateModel(
            name='FieldTranslationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('fr', 'French')], db_index=True, editable=False, max_length=15, verbose_name='Language')),
                ('label', models.CharField(blank=True, max_length=200, null=True, verbose_name='Label')),
                ('choices', models.CharField(blank=True, help_text='Comma separated options where applicable. If an option itself contains commas, surround the option starting with the `character and ending with the ` character.', max_length=1000, null=True, verbose_name='Choices')),
                ('default', models.CharField(blank=True, max_length=2000, null=True, verbose_name='Default value')),
                ('placeholder_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Placeholder Text')),
                ('help_text', models.CharField(blank=True, max_length=100, null=True, verbose_name='Help text')),
            ],
            options={
                'verbose_name': 'Field translation',
                'verbose_name_plural': 'Field translations',
                'ordering': ('field__order',),
                'abstract': False,
            },
            bases=(forms_builder.forms.models.CommaSeparatedChoiceMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FormTranslationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(choices=[('en', 'English'), ('de', 'German'), ('fr', 'French')], db_index=True, editable=False, max_length=15, verbose_name='Language')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Title')),
                ('slug', models.SlugField(blank=True, editable=False, max_length=100, null=True, unique=True, verbose_name='Slug')),
                ('intro', models.TextField(blank=True, null=True, verbose_name='Intro')),
                ('button_text', models.CharField(blank=True, default='Submit', max_length=50, null=True, verbose_name='Button text')),
                ('response', models.TextField(blank=True, null=True, verbose_name='Response')),
                ('redirect_url', models.CharField(blank=True, help_text='An alternate URL to redirect to after form submission', max_length=200, null=True, verbose_name='Redirect url')),
                ('email_from', models.EmailField(blank=True, help_text='The address the email will be sent from', max_length=254, null=True, verbose_name='From address')),
                ('email_copies', models.CharField(blank=True, help_text='One or more email addresses, separated by commas', max_length=200, null=True, verbose_name='Send copies to')),
                ('email_subject', models.CharField(blank=True, max_length=200, null=True, verbose_name='Subject')),
                ('email_message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('form', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='forms.Form')),
            ],
            options={
                'verbose_name': 'Form translation',
                'verbose_name_plural': 'Form translations',
            },
        ),
        migrations.AlterField(
            model_name='field',
            name='field_type',
            field=models.IntegerField(choices=[(1, 'Single line text'), (2, 'Multi line text'), (3, 'Email'), (13, 'Number'), (14, 'URL'), (4, 'Check box'), (5, 'Check boxes'), (6, 'Drop down'), (7, 'Multi select'), (8, 'Radio buttons'), (9, 'File upload'), (10, 'Date'), (11, 'Date/time'), (15, 'Date of birth'), (12, 'Hidden'), (100, 'My cool checkbox')], verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='fieldtranslationmodel',
            name='field',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='translation', to='forms.Field'),
        ),
        migrations.AddField(
            model_name='fieldtranslationmodel',
            name='form_translation',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='forms.FormTranslationModel'),
        ),
        migrations.AlterUniqueTogether(
            name='formtranslationmodel',
            unique_together=set([('form', 'language_code')]),
        ),
        migrations.AlterUniqueTogether(
            name='fieldtranslationmodel',
            unique_together=set([('field', 'language_code')]),
        ),
    ]
